base_repository: https://hg.mozilla.org/mozilla-central
head_ref: d6d4e8417d2fd71fdf47c319b7a217f6ace9d5a5
head_repository: https://hg.mozilla.org/mozilla-central/
head_rev: d6d4e8417d2fd71fdf47c319b7a217f6ace9d5a5
level: '3'
message: ' '
owner: cbook@mozilla.com
project: mozilla-central
pushlog_id: '30285'
revision_hash: 2b39b72c8ea987dc5599716e231e1f3c856aa4d0
target_tasks_method: all_tasks
